### ISSUE TITLE
image not loading

### ISSUE THREAD

**Issue by TeamSinkong** [CzechPMDevs/ImageOnMap#24]
![image](https://user-images.githubusercontent.com/73025791/202848274-df04e8db-9f43-4da4-8f49-1e878f87c10e.png)

The image will appear only when touching it.

help pls

**Comment by frizib** [comment]
+++

**Comment by VixikHD** [comment]
Your issue is missing certain information required for fixing the bug.

Without knowing your Plugin version, PocketMine-MP version, OS, PHP, Client version, other plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.

Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by Benedikt05** [comment]
@VixikHD #26!!
